### ISSUE TITLE
Volume and brightness control not working

### ISSUE THREAD

**Issue by santhoshraghul13** [xenon-19/Gesture-Controlled-Virtual-Mouse#14]
**Describe the bug**

After getting thumb and index close to each other, code stops running, could not perform brightness and volume control. Im running this in Python V-3.8.5.  I made no changes to the code
**To Reproduce**

**Expected behavior**
Every other feature works really good, but controlling fails for me.
**Screenshots**
![Scsht2](https://user-images.githubusercontent.com/106292116/170407160-cb36084c-79d4-42ff-93e2-f886d1fdcd7c.png)
![Scsht1](https://user-images.githubusercontent.com/106292116/170407397-d872b446-d6f8-4d6b-a602-0546a45e790f.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10

**Smartphone (please complete the following information):**

**Additional context**
[](url)

**Comment by ankit-4129** [comment]
TypeError: unsupported operand type(s) for /: 'float' and 'list'

You are getting this error because `get_brightness()`  returns a list if multiple displays are detected,
To fix this you should pass `display=0` to `get_brightness()` on line https://github.com/xenon-19/Gesture-Controlled-Virtual-Mouse/blob/a275d9d107f11d199d743b4dbfa467977439ed3b/src/Gesture_Controller.py#L292 and https://github.com/xenon-19/Gesture-Controlled-Virtual-Mouse/blob/a275d9d107f11d199d743b4dbfa467977439ed3b/src/Gesture_Controller.py#L298


I have pushed these changes in commit https://github.com/xenon-19/Gesture-Controlled-Virtual-Mouse/commit/a275d9d107f11d199d743b4dbfa467977439ed3b

Please let us know if this resolved your issue.

**Comment by LetMeKillMyself** [comment]
This did not fix it for Me I still have the exact same error

**Comment by fathysr** [comment]
I keep getting the same error
